#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <toolbox-container-name>" >&2
    exit 1
fi

declare CONTAINER="$1"
declare BACKEND=${2:-${CONTAINER#build-}}

toolbox run -c "$CONTAINER" bash -i ${0}.${BACKEND}

BUILD_STATUS=$?

if [ "$BUILD_STATUS" -eq 0 ]; then
    podman stop "$CONTAINER"
fi

exit "$BUILD_STATUS"
