FROM fedora:latest

RUN dnf -y update && \
    dnf -y install \
        coreutils \
        findutils \
        git \
	jq \
        less \
        which \
	procps-ng \
	sqlite \
        sudo \
        cmake \
        ninja-build \
	ccache \
        gcc \
        gcc-c++ \
	clang \
	clang-devel \
	compiler-rt \
	lld \
        npm \
	libcurl-devel \
	libicu-devel \
	libjpeg-turbo-devel \
	libpng-devel \
	libwebp-devel \
        openssl-devel \
	rdma-core-devel \
        vulkan-headers \
        vulkan-loader-devel \
	mesa-vulkan-drivers \
        spirv-headers-devel \
        glslc && \
    dnf clean all

COPY install-lemonade-server /usr/local/bin/

RUN --mount=type=secret,id=GITHUB_TOKEN \
    GITHUB_TOKEN=$(cat /run/secrets/GITHUB_TOKEN) /usr/local/bin/install-lemonade-server
