#!/bin/bash

declare baseurl=https://rocm.nightlies.amd.com/packages-multi-arch/rpm/ nightly_ver
nightly_ver=${
    curl -s $baseurl | sed -En -e 's/.*href="([^"]+)".*/\1/;s%index\.html%%p' | tail -1;
}

sudo dnf --repofrompath=rocm-nightly,"${baseurl}${nightly_ver}\$basearch" --setopt=rocm-nightly.gpgcheck=0 "${@}"
